
services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=ayzz
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=finpulse
    ports:
      - "5433:5432"
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+psycopg://ayzz:password123@db:5432/finpulse
    depends_on:
      - db

volumes:
  postgres_data:
    
